config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/', to: 'books#index'
  resources :books
  resources :authors, only: [:index, :show, :destroy]
  resources :genres, only: [:index, :show]
  resources :owned_books
  resources :requests
  resources :fav_genres, except: [:destroy]
  get '/users', to: 'users#index'
  get '/admins', to: 'admins#index'
  get '/find', to: 'books#find'
  get '/found_results', to: 'books#found_results'
  get '/search', to: 'books#search'
  # get '/requests/:id/action', to: 'requests#action', as: 'action_request'
  get '/request/:id/accept', to: 'requests#accept', as: 'accept_request'
  get '/request/:id/decline', to: 'requests#decline', as: 'decline_request'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :author_books, dependent: :destroy
  has_many :books, through: :author_books
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
  resourcify
  has_many :author_books, dependent: :destroy
  has_many :authors, through: :author_books

  has_many :book_genres, dependent: :destroy
  has_many :genres, through: :book_genres

  has_many :owned_books
  has_many :users, through: :owned_books, source: :user

  validates :title, presence: { message: "Please provide a title" }
  validates :authors, presence: { message: "Please provide at least one author" }
  validate :must_have_one_genre

  def must_have_one_genre
    if genre_ids.length < 1
      errors.add(:genre_ids, 'Please select at least one genre')
    end
  end 

  enum status: {
    valid: 0,
    invalid: 1
  }, _prefix: true
end

app/models/book_genre.rb
class BookGenre < ApplicationRecord
  belongs_to :book
  belongs_to :genre
end

app/models/fav_genre.rb
class FavGenre < ApplicationRecord
  belongs_to :user
  belongs_to :genre

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :book_genres, dependent: :destroy
  has_many :books, through: :book_genres

  has_many :fav_genres
  has_many :users, through: :fav_genres, source: :user
end

app/models/owned_book.rb
class OwnedBook < ApplicationRecord
  belongs_to :book
  belongs_to :user

  has_many :book_offered, class_name: "Request", foreign_key: :requester_book_id
  has_many :book_requested, class_name: "Request", foreign_key: :requestee_book_id

  has_one_attached :image, dependent: :purge

  scope :status_available, -> { where(status: 0) }


  enum condition: {
    new: 0,
    'like-new': 1,
    good: 2,
    'well-read': 3,
  }, _prefix: true

  enum format: {
    paperback: 0,
    hardcover: 1
  }, _prefix: true

  enum status: {
    available: 0,
    'out-of-stock': 1
  }, _prefix: true
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :requester, class_name: "User"
  belongs_to :requestee, class_name: "User"
  belongs_to :requester_book, class_name: "OwnedBook"
  belongs_to :requestee_book, class_name: "OwnedBook"

  scope :status_active, -> { where(status: 0) }
  scope :status_completed, -> { where.not(status: 0) }

  enum status: {
    pending: 0,
    cofirmed: 1,
    declined: 2,
    cancelled: 3,
    invalid: 4
  }, _prefix: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :admins, :join_table => :admins_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  after_commit :assign_default_role, on: :create

  has_many :owned_books
  has_many :books, through: :owned_books, source: :book

  has_many :fav_genres
  has_many :genres, through: :fav_genres, source: :genre

  has_many :requests_made, class_name: "Request", foreign_key: :requester_id
  has_many :requests_of, class_name: "Request", foreign_key: :requestee_id

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable 

  def assign_default_role
    add_role(:user) if roles.blank?
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/fav_genres_helper.rb
module FavGenresHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/owned_books_helper.rb
module OwnedBooksHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/index.html.erb
<div class="wrapper">
  <div>
    <h1>Owned Books List</h1>
    <ul>
      <% @owned_books.each do |book| %>
        <li><%= link_to book.book.title, owned_book_path(book.id) %></li>
      <% end %>
    </ul>
  </div>
  
  <div>
    <h1>Authors List</h1>
    <% if @authors_have_no_books.length == 0 %>
      <p>All authors have books under their name.</p>
    <% else %>
      <p>Below authors have no books under their name, it is better to clean that up.</p>
      <ul>
      <% @authors_have_no_books.each do |author| %>
        <li>
          <%= link_to author.name, author_path(author.id) %>
          <button><%= link_to "Delete", author_path(author.id), method: :delete, data: { confirm: "Are you sure?" }%></button>
        </li>
      <% end %>
    <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books that we loved</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cookie&family=Lato:wght@400;700&display=swap" rel="stylesheet"> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div>
        <%= render 'shared/navbar' %>
        <% if current_page?('/') || current_page?(books_path)%>
          <%= render 'shared/hero_pic' %>
        <% end %>
        <%= render 'shared/topbar' %>
        <% if flash[:errors] %>
        <section id="errors">
            <% flash[:errors].each do |error| %>
                <p><%= error %></p>
            <% end %>
        </section>
        <% end %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
      <div><%= render 'shared/footer' %></div>
    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-text">Designed and created by Rhona Lam</div>
</footer>

app/views/shared/_hero_pic.html.erb
<div class="hero-pic">
  <p class="hero-pic-text">share the books, share the love</p>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <div class="navbar-container">
    <div class="navbar-brand logo"><%= link_to "Books that we loved", books_path%></div>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li><%= current_user.username %></li>
        <li><%= link_to "Add New Book", find_path %></li>
        <li><%= link_to "Account", users_path %></li>
        <% if current_user.has_role? :admin %>
          <li><%= link_to "Admin", admins_path %></li>
        <% end %>
        <li><button class="btn btn-dark-outline"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li></button>
        <% else %>
        <li><button class="btn btn-dark-outline"><%= link_to "Login", new_user_session_path %></button></li>
        <li><button class="btn btn-dark"><%= link_to "Sign up", new_user_registration_path %></button></li>
      <% end %>
    </ul>
    <!-- Hamburger Menu -->
    <button type="button" class="hamburger" id="menu-btn">
      <span class="hamburger-top"></span>
      <span class="hamburger-middle"></span>
      <span class="hamburger-bottom"></span>
    </button>
  </div>
</nav>

<!-- Mobile Menu -->
<div class="mobile-menu hidden" id="menu">
  <ul class="mobile-menu-menu">
    <% if user_signed_in? %>
      <li><%= current_user.username %></li>
      <li><%= link_to "Add New Book", find_path %></li>
      <li><%= link_to "Account", users_path %></li>
  </ul>
  <ul class="mobile-menu-btns">
    <% if current_user.has_role? :admin %>
      <li><%= link_to "Admin", admins_path %></li>
    <% end %>
    <li><button class="btn btn-dark-outline"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li></button>
  <% else %>
    <li><button class="btn btn-dark-outline"><%= link_to "Login", new_user_session_path %></button></li>
    <li><button class="btn btn-dark"><%= link_to "Sign up", new_user_registration_path %></button></li>
  <% end %>
  </ul>
</div>

app/views/shared/_topbar.html.erb
<div class="top-bar">
    <div class="top-bar-top top-bar-search">
      <%= form_with url: '/search', method: :get do |f| %>
      <%= f.select :type, ['author', 'title'] %>
      <%= f.text_field :query %>
        <%= f.submit :search %>
      <% end %>
    </div>
    <div class="top-bar-bottom">
      <ul class="top-bar-menu">
        <li><%= link_to "BOOKS", books_path %></li>
        <li><%= link_to "AUTHORS", authors_path %></li>
        <li><%= link_to "GENRES", genres_path %></li>
      </ul>
    </div>
</div>