config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/', to: 'books#index'
  resources :books
  resources :authors, only: [:index, :show, :destroy]
  resources :genres, only: [:index, :show]
  resources :owned_books
  resources :requests
  resources :fav_genres, except: [:destroy]
  get '/users', to: 'users#index'
  get '/admins', to: 'admins#index'
  get '/find', to: 'books#find'
  get '/found_results', to: 'books#found_results'
  get '/search', to: 'books#search'
  # get '/requests/:id/action', to: 'requests#action', as: 'action_request'
  get '/request/:id/accept', to: 'requests#accept', as: 'accept_request'
  get '/request/:id/decline', to: 'requests#decline', as: 'decline_request'
end

app/models/user.rb
class User < ApplicationRecord
  after_commit :assign_default_role, on: :create

  has_many :owned_books
  has_many :books, through: :owned_books, source: :book

  has_many :fav_genres
  has_many :genres, through: :fav_genres, source: :genre

  has_many :requests_made, class_name: "Request", foreign_key: :requester_id
  has_many :requests_of, class_name: "Request", foreign_key: :requestee_id

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable 

  def assign_default_role
    add_role(:user) if roles.blank?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action -> { check_auth(User) }
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/fav.html.erb
<%= form_with url: '/add_fav_genres',  method: :get do |f| %>
  <%= f.collection_check_boxes :genres_id, @genres, :id, :name %>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<div class="wrapper users">
  <h1 class="title"><%= link_to "My Books", owned_books_path%></h1>
  <h1 class="title"><%= link_to "My Requests", requests_path%></h1>
  <h1 class="title"><%= link_to "My Favourite Genres", fav_genres_path%></h1>
</div>