config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/', to: 'books#index'
  resources :books
  resources :authors, only: [:index, :show, :destroy]
  resources :genres, only: [:index, :show]
  resources :owned_books
  resources :requests
  resources :fav_genres, except: [:destroy]
  get '/users', to: 'users#index'
  get '/admins', to: 'admins#index'
  get '/find', to: 'books#find'
  get '/found_results', to: 'books#found_results'
  get '/search', to: 'books#search'
  # get '/requests/:id/action', to: 'requests#action', as: 'action_request'
  get '/request/:id/accept', to: 'requests#accept', as: 'accept_request'
  get '/request/:id/decline', to: 'requests#decline', as: 'decline_request'
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :requester, class_name: "User"
  belongs_to :requestee, class_name: "User"
  belongs_to :requester_book, class_name: "OwnedBook"
  belongs_to :requestee_book, class_name: "OwnedBook"

  scope :status_active, -> { where(status: 0) }
  scope :status_completed, -> { where.not(status: 0) }

  enum status: {
    pending: 0,
    cofirmed: 1,
    declined: 2,
    cancelled: 3,
    invalid: 4
  }, _prefix: true
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!
  before_action -> { check_auth(Request) }
  before_action :get_request, only: [:show, :edit, :update, :destroy, :action, :accept, :decline]
  before_action :get_requestee_book, only: [:new]
  before_action :get_current_user_owned_books, only: [:new, :edit]
  before_action :get_current_user_requests_made, only: [:index]
  before_action :get_current_user_requests_of, only: [:index]
  before_action :get_all_requests_of_current_user, only: [:index]

  def index
  end
  
  def show; end

  def new
    @request = Request.new
  end

  def create
    if !params[:request].key? (:requester_book_id)
      redirect_to owned_book_path(params[:request][:requestee_book_id])
      flash[:notice] = "Sorry, you have no book to exchange."
    else
      @request = Request.new(request_params)
      @request.save
      redirect_to owned_book_path(params[:request][:requestee_book_id])
      flash[:notice] = "Request has sent to #{@request.requestee.username} successfully!"
    end
  end

  def edit
    if @request.requester == current_user
      @book = @request.requestee_book
    else
      redirect_to request_path(@request)
      flash[:alert] = "You are not authorized to perform this action."
    end
  end

  def update
    @request.update!(request_params)
    redirect_to request_path(@request.id)
    flash[:notice] = "Request has been updated successfully!"
  end

  def destroy
    @request.update(status: 3)
    redirect_to requests_path
    flash[:notice] = "Request has been deleted successfully!"
  end

  def action
  end

  def accept
    @request.update(status: 1)
    @request.requester_book.update(status: 1)
    @request.requestee_book.update(status: 1)
    get_requests_that_have_requester_and_requestee_books()
    @invalid_requests.each do |request|
      request.update(status: 4)
    end
  end

  def decline
    @request.update(status: 2)
  end

  private

  def get_request
    @request = Request.find(params[:id])
  end

  def get_current_user_requests_made
    @requests_made = current_user.requests_made.select(:id)
  end

  def get_current_user_requests_of
    @requests_received = current_user.requests_of.select(:id)
  end

  def get_requestee_book
    @book = OwnedBook.find(params[:requestee_book_id])
  end

  def get_current_user_owned_books
    @owned_books = current_user.owned_books.status_available
  end

  def request_params
    params.require(:request).permit(:requestee_id, :requester_id, :requestee_book_id, :requester_book_id)
  end

  def get_all_requests_of_current_user
    @all_requests = Request.where(requester_id: current_user.id).or(Request.where(requestee_id: current_user.id))
  end

  def get_requests_that_have_requester_and_requestee_books
    @invalid_requests = Request.status_active.where(requester_book: @request.requester_book).or(Request.status_active.where(requestee_book: @request.requestee_book))
  end


end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_confirmation.html.erb
<div class="wrapper action">
  <h1 class="title">Request has been <%= status %>, email confirmation has sent to <%= @request.requester.username %></h1>
  
  <button class="btn btn-dark"><%= link_to "Return to request page", requests_path %></button>
</div>

app/views/requests/_form.html.erb
<div class="wrapper request-form">
  <div>
    <h1 class="title request-title">Request Form</h1>
    
    <h3 class="sub-title">You are requesting for:</h3>
    <%= @book.book.title %>
    <h3 class="sub-title">Owned by</h3>
    <%= @book.user.username %>
    <h3 class="sub-title"><%= "#{@book.user.username}'s favourite genres: "%></h3>
    <ul>
      <% @book.user.fav_genres.each do |genre| %>
        <li><%= genre.genre.name.capitalize %></li>
      <% end %>
    </ul>
    <p>- - - -</p>
    <h3 class="sub-title">Book that you want to use to exchange:</h3>
    
    <%= form_with model: @request do |f| %>
      <%= f.hidden_field :requester_id, value: current_user.id %>
      <%= f.hidden_field :requestee_id, value: @book.user.id %>
      <%= f.hidden_field :requestee_book_id, value: requestee_book_id %>
      <% @owned_books.each do |b| %>
        <%= f.radio_button :requester_book_id, b.id, checked: "checked" %>
        <%= f.label :title, b.book.title %>
      <% end %>
      <div class="submit"><%= f.submit "Send", class: 'btn btn-dark' %></div>
    <% end %>
  </div>
</div>

app/views/requests/accept.html.erb
<%= render partial: 'confirmation', locals: { status: 'accepted'} %>

app/views/requests/decline.html.erb
<%= render partial: 'confirmation', locals: { status: 'declined'} %>

app/views/requests/edit.html.erb
<%= render partial: 'form', locals: {requestee_book_id: @request.requestee_book_id} %>

app/views/requests/index.html.erb
<div class="wrapper requests">
  <div class="current-requests">
    <h1 class="title">Current Requests</h1>
    <h3 class="sub-title">To be confirmed</h3>
    <ul>
      <% @requests_received.status_active.each do |request| %>
        <li><%= link_to request.id, request_path(request.id) %></li>
      <% end %>
    </ul>
    <h3 class="sub-title">Awaiting Response</h3>
    <ul>
      <% @requests_made.status_active.each do |request| %>
        <li><%= link_to request.id, request_path(request.id) %></li>
    <% end %>
    </ul>
  </div>
  <div class="past-requests">
    <h1 class="title">Past Requests</h1>
    <ul>
      <ul>
        <% @all_requests.status_completed.each do |request| %>
          <li><%= link_to request.id, request_path(request.id) %></li>
      <% end %>
      </ul>
    </ul>
  </div>
</div>

app/views/requests/new.html.erb
<%= render partial: 'form', locals: {requestee_book_id: params[:requestee_book_id]} %>

app/views/requests/show.html.erb
<div class="wrapper request-show">
  <div class="request">
    <h1 class="title request-title">Request No. <%= @request.id %></h1>
    <h3 class="sub-title">Send from:</h3>
      <%= @request.requester.username%>
    <h3 class="sub-title">Send to:</h3>
      <%= @request.requestee.username%>
    <h3 class="sub-title">Request for:</h3>
      <%= link_to @request.requestee_book.book.title, owned_book_path(@request.requestee_book.id)%>
    
    <h3 class="sub-title">Offer:</h3>
    <%= link_to @request.requester_book.book.title, owned_book_path(@request.requester_book.id)%>
    
    <h3 class="sub-title">Status:</h3>
    <%= @request.status.capitalize %>
    <div class="requests-btns">
      <% if @request.status == 'pending' %>
        <% if @request.requester_id == current_user.id %>
        <button class="btn btn-dark"><%= link_to "Edit", edit_request_path(@request.id)%></button>
        <button class="btn btn-dark"><%= link_to "Cancel", request_path(@request.id), method: :delete, data: { confirm: "Are you sure?"} %></button>
        <% else %>
        <button class="btn btn-dark"><%= link_to "Accept request", accept_request_path(@request.id)%></button>
        <button class="btn btn-dark"><%= link_to "Decline request", decline_request_path(@request.id)%></button>
        <% end %>
        <% elsif @request.status == 'invalid' %>
          <h3 class="sub-title">Note:</h3>
          <p class="note">Unfortunately one of the book is no longer available.</p>
      <% end %>
    </div>
  </div>
  
  
  
</div>