config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/', to: 'books#index'
  resources :books
  resources :authors, only: [:index, :show, :destroy]
  resources :genres, only: [:index, :show]
  resources :owned_books
  resources :requests
  resources :fav_genres, except: [:destroy]
  get '/users', to: 'users#index'
  get '/admins', to: 'admins#index'
  get '/find', to: 'books#find'
  get '/found_results', to: 'books#found_results'
  get '/search', to: 'books#search'
  # get '/requests/:id/action', to: 'requests#action', as: 'action_request'
  get '/request/:id/accept', to: 'requests#accept', as: 'accept_request'
  get '/request/:id/decline', to: 'requests#decline', as: 'decline_request'
end

app/models/book.rb
class Book < ApplicationRecord
  resourcify
  has_many :author_books, dependent: :destroy
  has_many :authors, through: :author_books

  has_many :book_genres, dependent: :destroy
  has_many :genres, through: :book_genres

  has_many :owned_books
  has_many :users, through: :owned_books, source: :user

  validates :title, presence: { message: "Please provide a title" }
  validates :authors, presence: { message: "Please provide at least one author" }
  validate :must_have_one_genre

  def must_have_one_genre
    if genre_ids.length < 1
      errors.add(:genre_ids, 'Please select at least one genre')
    end
  end 

  enum status: {
    valid: 0,
    invalid: 1
  }, _prefix: true
end

app/models/user.rb
class User < ApplicationRecord
  after_commit :assign_default_role, on: :create

  has_many :owned_books
  has_many :books, through: :owned_books, source: :book

  has_many :fav_genres
  has_many :genres, through: :fav_genres, source: :genre

  has_many :requests_made, class_name: "Request", foreign_key: :requester_id
  has_many :requests_of, class_name: "Request", foreign_key: :requestee_id

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable 

  def assign_default_role
    add_role(:user) if roles.blank?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action -> { check_auth(Book) }, except: [:search]
  before_action :get_params, only: [:new]
  before_action :get_genres, only: [:new, :create, :edit, :update]
  before_action :get_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.select(:title, :id, :cover, :status).status_valid
  end

  def show
  end

  def new
    begin
      book = Book.find_by(book_api_id: params[:book_api_id])
      if !book.nil?
        book.update(status: 0)
        redirect_to book_path(book)
        flash[:notice] = "Please click swap to add your book to this platform."
      else
        @book = Book.new
      end
    rescue
      flash.now[:error] = "Our apologise, something went wrong, please try again!"
      render 'search'
    end
  end

  def create
    begin
      if Book.find_by(book_api_id: params[:book][:book_api_id]).nil?
        @book = Book.new(book_params)
        add_or_edit_authors(@book)
        @book.save!
      end
      redirect_to new_owned_book_path(title: "#{@book.title}")
      flash[:notice] = "Book is added to library, please continue to add your book for swap"
    rescue
      get_params()
      flash.now[:errors] = @book.errors.messages.values.flatten
      render 'new'
    end
  end

  def edit
    @genres = Genre.select(:id, :name)
  end

  def update
    @book.update(book_params)
    @book.authors.destroy_all
    add_or_edit_authors(@book)
    begin
      @book.save!
      redirect_to book_path(@book.id)
      flash[:notice] = "Book has updated successfully!"
    rescue
      flash.now[:errors] = @book.errors.messages.values.flatten
      render 'edit'
    end
  end

  def destroy
    @affected_ownedbooks = OwnedBook.select(:id, :book_id, :status, :user_id).where(book_id: @book.id).status_available
    if @affected_ownedbooks.length > 0
      flash[:notice] = "Sorry, this book cannot be deleted as there is owned book linked to this book!"
      render 'show'
    else
      @book.update(status: 1)
      flash[:notice] = "Book has been destroyed successfully!"
      redirect_to books_path
    end
  end

  # Search bar
  def search
    case params[:type]
    when 'author'
      @authors = Author.where("LOWER(name) LIKE LOWER(?)", "%#{params[:query]}%")
      render "authors/index"
    when 'title'
      @books = Book.where("LOWER(title) LIKE LOWER(?)", "%#{params[:query]}%")
      render 'index'
    end
  end
  # Progress to add new book
  def find; end

  def found_results
    @books = GoogleBooks.search("intitle:#{params[:find]}")
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :book_api_id, :cover, genre_ids: [])
  end

  def get_genres
    @genres = Genre.select(:id, :name)
  end

  def get_params
    @title = params[:title] || params[:book][:title]
    @authors = params[:authors] || params[:book][:authors]
    @description = params[:description] || params[:book][:description]
    @book_api_id = params[:book_api_id] || params[:book][:book_api_id]
    @cover = params[:cover] || params[:book][:cover]
  end

  def get_book
    @book = Book.find(params[:id])
  end

  def add_or_edit_authors(book)
    @authors_array = params[:book][:authors].split(', ')
    @authors_array.each do |author|
      if Author.find_by(name: author).nil?
        Author.create(name: author)
      end
      book.authors << Author.find_by(name: author)
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="wrapper edit-book">
  <div class="edit-book-form">
    <h1>Edit Book</h1>
    <h3 class="sub-title"><%= @book.title %></h3>
    
    <div>
      <%= form_with model: @book do |f| %>
      <div>
        <%= f.hidden_field :title, value: @book.title %>
        <div>
          <%= f.label :authors %>
          <%= f.text_field :authors, value: @book.authors.map { |a| a.name }.join(', ') %>
        </div>
        <div>
          <%= f.label :description %>
          <%= f.text_area :description, value: @book.description %>
        </div>
        <%= f.hidden_field :book_api_id, value: @book.book_api_id %>
        <%= f.hidden_field :cover, value: @book.cover %>
      </div>
      <div class="genres">
        <h3><%= f.label :genres, "Genres:" %></h3>
        <%= f.collection_check_boxes :genre_ids, @genres, :id, :name %>
      </div>
    
      <div>
        <div class="submit"><%= f.submit "Update", class: 'btn btn-dark' %></div>
      </div>
      <% end %>
    </div>
  </div>
  
</div>

app/views/books/find.html.erb
<div class="wrapper find_book">
  <div>
    <h1 class="title find_book_title">Add New Book</h1>
    
    <%= form_with url: "/found_results", method: :get do |f| %>
    <div class="search-bar">
      <%= f.label :find, "Book Title:" %>
      <%= f.text_field :find, placeholder: "Book Title" %>
      <div class="search-btn">
        <div class="submit"><%= f.submit "Search", class: 'btn btn-dark' %></div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/books/found_results.html.erb
<div class="wrapper found-results">
  <h1 class="title">Which book are you searching?</h1>
  
  <div class="page-wrapper">
      <% @books.each do |book| %>
      <div class="found_book_wrapper">
      <% if book.image_link.nil? %>
          <div><%= image_tag("no_image.png") %></div>
        <% else %>
          <div><img src="<%= book.image_link %>" alt="Book cover of <%= "#{book.title}" %>"></div>
        <% end %>
        <div><%= link_to book.title, new_book_path + "?title=#{ERB::Util.url_encode(book.title)}&authors=#{book.authors_array.map { |a| a }.join(", ")}&book_api_id=#{book.id}&cover=#{ERB::Util.url_encode(book.image_link)}&description=#{ERB::Util.url_encode(book.description)}" %></div>
      </div>
      <% end %>
  </div>
  
  <p class="return"><%= link_to "<< Can't see your book here? Go back and search again.", :back %></p>
  <p class="tips">Tips: Try a full book title 😊</p>
</div>

app/views/books/index.html.erb
<div class="page-wrapper">
  <% @books.each do |book| %>
    <div class="book-wrapper">
      <div class="book-wrapper-image"><img src="<%= book.cover %>" alt="Book cover of <%= "#{book.title}" %>"></div>
      <div class="book-wrapper-body"><%= link_to book.title, book_path(book.id) %></div>
    </div>
  <% end %>
</div>

app/views/books/new.html.erb
<div class="wrapper add-new-book">
  <div class="add-new-book-form">
    <h1 class="title">Add book to the library</h1>
    <div>
      <div>
        <img src="<%= @cover %>" alt="Book cover">
        <div>
          <h1 class="title"><%= @title %></h1>
          <h1 class="title">By <%= @authors %></h1>
        </div>
      </div>
      <h3 class="sub-title">Description: </h3>
      <% if @book.values_at(:description).present? %>
          <%= @description %>
        <% else %>
          <%= "n/a" %>
      <% end %>
    </div>
    
    <div>
      <%= form_with model: @book do |f| %>
      <div>
        <%= f.hidden_field :title, value: @title %>
        <%= f.hidden_field :authors, value: @authors %>
        <%= f.hidden_field :description, value: @description %>
        <%= f.hidden_field :book_api_id, value: @book_api_id %>
        <%= f.hidden_field :cover, value: @cover %>
      </div>
      <div>
        <h3 class="sub-title"><%= f.label :genres, "Please select suitable genres for this book:" %></h3>
        <%= f.collection_check_boxes :genre_ids, @genres, :id, :name %>
      </div>
    
      <div>
        <div class="submit"><%= f.submit "Add", class: 'btn btn-dark' %></div>
      </div>
    <% end %>
    </div>
  </div>
  
</div>

app/views/books/search.html.erb
<h1>Add New Book</h1>

<%= form_with url: "/search_results", method: :get do |f| %>
<div class="search-bar">
  <%= f.label :search, "Book Title:" %>
  <%= f.text_field :search, placeholder: "Book Title" %>
  <div class="search-bar-btn">
    <%= f.submit "Search for book"%>
  </div>
</div>
<% end %>

app/views/books/search_results.html.erb
<h1>Which book are you searching?</h1>

<div class="results_wrapper">
    <% @books.each do |book| %>
    <div class="searched_book_wrapper">
      <% if book.image_link.nil? %>
        <%= image_tag("book_cover.png") %>
      <% else %>
        <img src="<%= book.image_link %>" alt="Book cover of <%= "#{book.title}" %>">
      <% end %>
      <%= link_to book.title, new_book_path + "?title=#{book.title}&authors=#{book.authors_array.map { |a| a }.join(", ")}&book_api_id=#{book.id}&cover=#{ERB::Util.url_encode(book.image_link)}&description=#{book.description}" %>
    </div>
    <% end %>
</div>

<p><%= link_to "<< Can't see your book here? Go back and search again. Tips: It will be easier to find your book with full title", :back %></p>

app/views/books/show.html.erb
<div class="wrapper show-book">
  <div class="book-page-wrapper">
    <div  class="book-side">
      <div class="book-side-main">
        <div class="book-cover"><img src="<%= @book.cover %>" alt="Book cover"></div>
        <div>
          <h1 class="book-title title"><%= @book.title %></h1>
          <h2 class="book-author title">By <%= safe_join(@book.authors.map{ |a| link_to(a.name, author_path(a.id)) }, ", ".html_safe) %></h2>
          <h3 class="book-genres sub-title">Genres:
          <%= safe_join(@book.genres.map{ |g| link_to(g.name.capitalize, genre_path(g.id)) }, ", ".html_safe) %></h3>
        </div>
      </div>
      <div>
        <h3 class="sub-title">Description:</h3>
        <div class="book-description"><%= @book.description %></div>
        <% if current_user && policy(@book).edit? %>
          <button class="btn btn-dark"><%= link_to "Edit", edit_book_path(@book.id) %></button>
        <% end %>
        <% if current_user && policy(@book).destroy? %>
          <button class="btn btn-dark"><%= link_to "Delete", book_path(@book.id), method: :delete, data: { confirm: "Are you sure?" } %></button>
        <% end %>
      </div>
    </div>
  
    <div class="request-side">
      <div class="request-top">
        <h3 class="sub-title">You have one that want to swap?</h3>
        <button class="btn btn-dark"><%= link_to "Click here", new_owned_book_path + "?title=#{@book.title}" %></button>
      </div>
  
      <div class="request-bottom">
        <h3 class="sub-title">List of owners: </h3>
        <% if @book.owned_books.status_available.empty? %>
        <p>None at the moment</p>
        <% else %>
        <ul>
          <% @book.owned_books.status_available.each do |owned_book| %>
          <li><%= link_to owned_book.user.username, owned_book_path(owned_book.id) %></li>
          <% end %>
        </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>